Hidra lerna Objetivo 3
josevilchez247/Odyssey pull request #22
Opened 2022-09-01 10:46 UTC by josevilchez247

Elección de gestor de tareas y de gestor de dependencias además de la implementación de los ficheros necesarios para la utilización de estas herramientas. Con esto se avanza en el [M4 Automatización de tareas (https://github.com/josevilchez247/Odyssey/issues/21) 

* [x]  ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x]  ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x]  ¿Ese issue está asignado a un milestone?
* [x]  ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x]  ¿El PR, que también es un issue, está asignado al mismo milestone?

2022-09-02 07:32 UTC, JJ requested changes
No has justificado el gestor de dependencias.

2022-09-02 07:32 UTC, JJ commented on docs/task_runner.md
> +un servicio y para desplegar este servicio voy a utilizar Docker, teniendo esto en cuenta necesito un gestor de tareas que se pueda integrar bien con Docker.
No hay ningún gestor de tareas que no cumpla esto.

2022-09-02 07:32 UTC, JJ commented on docs/task_runner.md
> +Otro punto a tener en cuenta es el lenguaje del proyecto, en este caso Python, por tanto, necesito un gestor de tareas adecuado para este lenguaje.
Esto es bastante ambiguo y no está claro qué significa.

2022-09-02 07:35 UTC, josevilchez247 commented
@JJ El gestor de dependencias como leí en el guion que no era necesario justificar su elección por eso no lo he añadido

2022-09-02 07:39 UTC, josevilchez247 commented on docs/task_runner.md
> +un servicio y para desplegar este servicio voy a utilizar Docker, teniendo esto en cuenta necesito un gestor de tareas que se pueda integrar bien con Docker.
Poethepoet cumple eso y además de cumplirlo funciona muy bien con Poetry que es el gestor de dependencias que voy a utilizar, ya que me da mucha mas facilidad a la hora de definir las tareas en el mismo fichero pyproject.toml o incluso podría definir las tareas en un script y me permitiría ejecutar ese script

2022-09-02 07:41 UTC, JJ commented
> @JJ El gestor de dependencias como leí en el guion que no era necesario justificar su elección por eso no lo he añadido

Te estoy diciendo que sí hace falta. Lo que dice el guión es que hay que justificar en caso de que el gestor de dependencias y el de tareas sean el mismo.

2022-09-02 08:31 UTC, josevilchez247 commented
@JJ ya he añadido la justificación del gestor de dependencias

2022-09-02 09:37 UTC, JJ commented on docs/task_runner.md
> +un servicio y para desplegar este servicio voy a utilizar Docker, teniendo esto en cuenta necesito un gestor de tareas que se pueda integrar bien con Docker.
No es que funcione bien con poetry, es que no funciona de otra forma.
En todo caso, tendrás que justificar qué hace que funcione bien con Docker y que otros (no has mencionado ninguno) no lo hacen.

2022-09-02 09:47 UTC, josevilchez247 commented on docs/task_runner.md
> +Tras la elección del task runner (POETHEPOET) hay que elegir un gestor de dependencias, un criterio esencial es que el task runner y el gestor de dependecias trabajen
Sí lo sé, pero en este caso en el archivo pyproject.toml no lo he puesto como plugin sino de forma independiente

2022-09-02 09:49 UTC, josevilchez247 commented on docs/task_runner.md
> +Tras la investigación he podido leer a cerca de varios gestores de dependencias para Python:
Primero he elegido el task runner ya que como ve lo he cambiado, antes usaba invoke, y ahora he decidido usar mejor poethepoet y una vez elegí ese task runner vi que la mejor opción era usar poetry.

2022-09-02 09:50 UTC, josevilchez247 commented on docs/task_runner.md
> +2- POETRY: Poetry es una herramienta para la gestión de dependencias y el empaquetado en Python. El archivo pyproject.toml es lo mas importante ya que será el encargado de manejar el proyecto y gesti
Cierto se me ha olvidado añadirlo

2022-09-02 09:50 UTC, JJ commented on docs/task_runner.md
> +Tras la elección del task runner (POETHEPOET) hay que elegir un gestor de dependencias, un criterio esencial es que el task runner y el gestor de dependecias trabajen
Entonces no necesita a poetry.

2022-09-02 09:51 UTC, JJ commented on docs/task_runner.md
> +2- POETRY: Poetry es una herramienta para la gestión de dependencias y el empaquetado en Python. El archivo pyproject.toml es lo mas importante ya que será el encargado de manejar el proyecto y gesti
Pero ¿lo has probado o no lo has probado? hatch tiene algo en común con poethepoet y poetry. ¿Sabes qué?

2022-09-02 09:53 UTC, josevilchez247 commented on docs/task_runner.md
> +Tras la elección del task runner (POETHEPOET) hay que elegir un gestor de dependencias, un criterio esencial es que el task runner y el gestor de dependecias trabajen
De acuerdo

2022-09-02 09:56 UTC, JJ commented on docs/task_runner.md
> +Tras la investigación he podido leer a cerca de varios gestores de dependencias para Python:
Porque poetry y poethepoet usan...

2022-09-05 13:46 UTC, josevilchez247 commented on docs/task_runner.md
> +Tras la investigación he podido leer a cerca de varios gestores de dependencias para Python:
Ambos usan el mismo fichero pyproject.toml no sé si se refiere a eso

2022-09-05 14:04 UTC, josevilchez247 commented on docs/task_runner.md
> +bien entre sí, además de ser adecuado para el lenguaje de nuestro proyecto (Python).
No se a que se refiere con elección que he tomado previa a elegir poethepoet y poetry, no he elegido nada más

2022-09-05 14:09 UTC, josevilchez247 commented on docs/task_runner.md
> +Tras la investigación he podido leer a cerca de varios gestores de dependencias para Python:
Usan el mismo entorno virtual

2022-09-05 14:11 UTC, josevilchez247 commented on docs/task_runner.md
> +2- POETRY: Poetry es una herramienta para la gestión de dependencias y el empaquetado en Python. El archivo pyproject.toml es lo mas importante ya que será el encargado de manejar el proyecto y gesti
No lo he probado solo investigué a cerca de él pero lo miré cuando estaba en el PR anterior.

2022-09-05 14:22 UTC, josevilchez247 commented on docs/task_runner.md
> +2- POETRY: Poetry es una herramienta para la gestión de dependencias y el empaquetado en Python. El archivo pyproject.toml es lo mas importante ya que será el encargado de manejar el proyecto y gesti
Hacth es muy parecido a estos dos mencionados anteriormente para definir las tareas puedes utilizar también el archivo pyproject.toml o hatch.toml y al igual que poethepoet puede usar el mismo entorno virtual para trabajar bien con poetry

2022-09-05 16:34 UTC, JJ commented on docs/task_runner.md
> +Tras la investigación he podido leer a cerca de varios gestores de dependencias para Python:
Y además usan...

2022-09-05 16:35 UTC, JJ commented on docs/task_runner.md
> +bien entre sí, además de ser adecuado para el lenguaje de nuestro proyecto (Python).
Si lo has hecho, solo que no te has dado cuenta. En el momento que decides que vas a gestionar las dependencias con `pyproject.toml`, ¿qué opciones tenías para gestor de dependencias? ¿Qué opciones eran las mejores para un fichero de tareas?

2022-09-07 11:38 UTC, JJ approved these changes
No has contestado a la mitad de las objeciones que te he hecho. Por favor, hazlo, pero un PR aparte antes de pasar al siguiente objetivo.
Hemos llegado al punto en que no se puede mejorar más, así que vamos a darlo por hecho, pero por favor, trata de entender lo que se busca y lo que se pide en los objetivos sucesivos.

2022-09-07 11:38 UTC, JJ commented on README.md
> +Para comprobar si la instalación se ha realizado de forma exitosa podemos hacer
ya te he dicho varias veces que esto no aporta nada.

2022-09-07 11:38 UTC, JJ commented on docs/task_runner.md
> +2- POETRY: Poetry es una herramienta para la gestión de dependencias y el empaquetado en Python. El archivo pyproject.toml es lo mas importante ya que será el encargado de manejar el proyecto y gesti
Entonces si trabaja con pyproject.toml, podrá funcionar también con poethepoet, ¿no?

2022-09-07 11:38 UTC, JJ commented on pyproject.toml
> +description = "Calcula la ruta mas optima para el repostaje de gasolina en un viaje"
Corrige las faltas de ortografía, por favor.

2022-09-07 12:04 UTC, merged